(function(){
// Meal database. Categories: "vegan", "high-protein", "standard".
// A meal can belong to multiple categories (e.g. vegan + high-protein).
// Ingredient units are normalized so the shopping list can sum them:
//   g (grams), ml, tbsp, tsp, cup, clove, piece, can, slice
// "aisle" groups ingredients on the shopping list.

const AISLES = {
  produce: "Produce",
  protein: "Meat & Seafood",
  plantProtein: "Plant Protein",
  dairy: "Dairy & Eggs",
  pantry: "Pantry",
  grains: "Grains & Bread",
  frozen: "Frozen",
  spice: "Spices & Herbs",
  condiment: "Condiments & Oils",
};

// Sources use search URLs on well-known recipe sites so users can pick
// the specific version they prefer (avoids linking to articles that may move).
const src = (name, site = "cooking.nytimes.com") => ({
  name,
  url: `https://www.google.com/search?q=${encodeURIComponent(name + " recipe site:" + site)}`,
});

const MEALS = [
  // ───────────── STANDARD ─────────────
  {
    id: "chicken-parm",
    name: "Crispy Chicken Parmesan",
    categories: ["standard", "high-protein"],
    emoji: "🍗",
    color: "from-amber-200 to-rose-200",
    blurb: "Panko-crusted chicken, marinara, melted mozzarella over spaghetti.",
    time: 35, calories: 720, protein: 52,
    ingredients: [
      { name: "Chicken breast", qty: 450, unit: "g", aisle: "protein" },
      { name: "Panko breadcrumbs", qty: 1, unit: "cup", aisle: "pantry" },
      { name: "Marinara sauce", qty: 1, unit: "cup", aisle: "pantry" },
      { name: "Mozzarella cheese", qty: 150, unit: "g", aisle: "dairy" },
      { name: "Spaghetti", qty: 225, unit: "g", aisle: "grains" },
      { name: "Egg", qty: 1, unit: "piece", aisle: "dairy" },
      { name: "Parmesan", qty: 40, unit: "g", aisle: "dairy" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Preheat oven to 220°C / 425°F. Butterfly the chicken breasts and pound to ½-inch thick.",
      "Set up dredge: beaten egg in one bowl, panko mixed with half the parmesan in another. Season chicken, dip in egg, press into panko.",
      "Heat olive oil in an oven-safe skillet and sear chicken 2–3 min per side until golden.",
      "Spoon marinara over each piece, top with mozzarella and remaining parmesan. Bake 10–12 min until cheese bubbles.",
      "Meanwhile cook spaghetti in salted water until al dente. Serve chicken over pasta with extra sauce.",
    ],
    source: src("Chicken parmesan", "cooking.nytimes.com"),
  },
  {
    id: "beef-tacos",
    name: "Smoky Beef Street Tacos",
    categories: ["standard", "high-protein"],
    emoji: "🌮",
    color: "from-orange-200 to-red-200",
    blurb: "Seasoned ground beef, lime crema, charred corn tortillas.",
    time: 25, calories: 610, protein: 38,
    ingredients: [
      { name: "Ground beef", qty: 450, unit: "g", aisle: "protein" },
      { name: "Corn tortillas", qty: 8, unit: "piece", aisle: "grains" },
      { name: "Sour cream", qty: 0.5, unit: "cup", aisle: "dairy" },
      { name: "Lime", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Red onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cotija cheese", qty: 50, unit: "g", aisle: "dairy" },
      { name: "Cumin", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Smoked paprika", qty: 1, unit: "tsp", aisle: "spice" },
    ],
    steps: [
      "Finely dice red onion and soak half in cold water. Chop cilantro, cut limes into wedges.",
      "Brown ground beef over medium-high heat, breaking it up. Drain fat, then stir in cumin, smoked paprika, salt, and a splash of water; simmer 3 min.",
      "Mix sour cream with lime juice and a pinch of salt to make a quick crema.",
      "Char tortillas directly over a gas flame or in a dry skillet, 15 sec per side.",
      "Build tacos: beef, drained onion, cotija, cilantro, crema, lime.",
    ],
    source: src("Ground beef street tacos", "seriouseats.com"),
  },
  {
    id: "honey-garlic-salmon",
    name: "Honey Garlic Glazed Salmon",
    categories: ["standard", "high-protein"],
    emoji: "🐟",
    color: "from-rose-200 to-orange-200",
    blurb: "Pan-seared salmon, sticky honey-garlic glaze, jasmine rice, broccoli.",
    time: 25, calories: 640, protein: 44,
    ingredients: [
      { name: "Salmon fillet", qty: 500, unit: "g", aisle: "protein" },
      { name: "Jasmine rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Broccoli", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Honey", qty: 3, unit: "tbsp", aisle: "pantry" },
      { name: "Soy sauce", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { name: "Sesame seeds", qty: 1, unit: "tbsp", aisle: "pantry" },
    ],
    steps: [
      "Start rice per package directions. Cut broccoli into florets.",
      "Whisk honey, soy sauce, grated garlic and ginger, and 1 tbsp water for the glaze.",
      "Pat salmon dry, salt it. Sear skin-side up in a hot oiled pan for 3 min, flip, cook 2 min more.",
      "Pour glaze into the pan, spooning over salmon until thick and sticky, about 90 seconds.",
      "Steam broccoli 4 min. Serve salmon on rice with broccoli, spooning glaze over. Finish with sesame seeds.",
    ],
    source: src("Honey garlic salmon", "cooking.nytimes.com"),
  },
  {
    id: "chicken-alfredo",
    name: "Creamy Chicken Alfredo",
    categories: ["standard"],
    emoji: "🍝",
    color: "from-yellow-100 to-amber-200",
    blurb: "Fettuccine tossed in silky parmesan cream with seared chicken.",
    time: 30, calories: 780, protein: 42,
    ingredients: [
      { name: "Chicken breast", qty: 400, unit: "g", aisle: "protein" },
      { name: "Fettuccine", qty: 225, unit: "g", aisle: "grains" },
      { name: "Heavy cream", qty: 1, unit: "cup", aisle: "dairy" },
      { name: "Parmesan", qty: 80, unit: "g", aisle: "dairy" },
      { name: "Butter", qty: 3, unit: "tbsp", aisle: "dairy" },
      { name: "Garlic", qty: 3, unit: "clove", aisle: "produce" },
      { name: "Parsley", qty: 1, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Boil fettuccine in salted water until just shy of al dente; reserve 1 cup pasta water.",
      "Slice chicken into cutlets, season, and sear in butter 3–4 min per side. Rest, then slice.",
      "In the same pan, melt remaining butter, add minced garlic, cook 30 sec. Add cream and simmer 2 min.",
      "Off heat, whisk in grated parmesan. Toss in drained pasta, loosening with pasta water as needed.",
      "Top with sliced chicken, chopped parsley, and a generous grind of black pepper.",
    ],
    source: src("Fettuccine Alfredo with chicken", "bonappetit.com"),
  },
  {
    id: "pork-stirfry",
    name: "Ginger Pork Stir-Fry",
    categories: ["standard"],
    emoji: "🥢",
    color: "from-lime-200 to-emerald-200",
    blurb: "Quick-seared pork with snap peas, bell peppers, and ginger-soy glaze.",
    time: 20, calories: 560, protein: 36,
    ingredients: [
      { name: "Pork tenderloin", qty: 450, unit: "g", aisle: "protein" },
      { name: "Snap peas", qty: 200, unit: "g", aisle: "produce" },
      { name: "Bell pepper", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Ginger", qty: 2, unit: "tbsp", aisle: "produce" },
      { name: "Soy sauce", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Jasmine rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Sesame oil", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Garlic", qty: 3, unit: "clove", aisle: "produce" },
    ],
    steps: [
      "Start rice. Slice pork tenderloin thin across the grain; toss with 1 tbsp soy sauce and a pinch of cornstarch if you have it.",
      "Mince ginger and garlic. Slice bell peppers. Trim snap peas.",
      "Heat a wok or skillet until smoking. Sear pork in a single layer 1 min, flip, 1 min more. Remove.",
      "Add a touch of oil, stir-fry peppers and snap peas 2 min. Add garlic and ginger, 30 sec.",
      "Return pork, splash in remaining soy and sesame oil. Toss and serve over rice.",
    ],
    source: src("Ginger pork stir fry", "seriouseats.com"),
  },
  {
    id: "turkey-meatballs",
    name: "Mediterranean Turkey Meatballs",
    categories: ["standard", "high-protein"],
    emoji: "🧆",
    color: "from-amber-100 to-orange-200",
    blurb: "Herbed turkey meatballs, lemon orzo, tzatziki, cucumber salad.",
    time: 35, calories: 620, protein: 48,
    ingredients: [
      { name: "Ground turkey", qty: 500, unit: "g", aisle: "protein" },
      { name: "Orzo", qty: 200, unit: "g", aisle: "grains" },
      { name: "Greek yogurt", qty: 1, unit: "cup", aisle: "dairy" },
      { name: "Cucumber", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Lemon", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Feta cheese", qty: 80, unit: "g", aisle: "dairy" },
      { name: "Dill", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 3, unit: "clove", aisle: "produce" },
    ],
    steps: [
      "Grate half the cucumber, squeeze out liquid. Mix with yogurt, 1 minced garlic clove, chopped dill, salt, and lemon juice → tzatziki.",
      "Combine turkey with remaining grated garlic, chopped dill, salt, pepper, and a splash of water. Roll into 20 meatballs.",
      "Sear meatballs in a hot oiled skillet, turning until browned and cooked through, about 8 min.",
      "Boil orzo in salted water per package. Drain, toss with lemon zest, juice, and a drizzle of olive oil.",
      "Plate orzo, meatballs, tzatziki, remaining sliced cucumber, and crumbled feta.",
    ],
    source: src("Turkey meatballs with tzatziki and orzo", "cooking.nytimes.com"),
  },
  {
    id: "shrimp-scampi",
    name: "Lemon Butter Shrimp Scampi",
    categories: ["standard", "high-protein"],
    emoji: "🍤",
    color: "from-yellow-200 to-lime-200",
    blurb: "Garlic-butter shrimp over linguine with a bright lemon finish.",
    time: 20, calories: 590, protein: 40,
    ingredients: [
      { name: "Shrimp", qty: 450, unit: "g", aisle: "protein" },
      { name: "Linguine", qty: 225, unit: "g", aisle: "grains" },
      { name: "Butter", qty: 4, unit: "tbsp", aisle: "dairy" },
      { name: "Garlic", qty: 5, unit: "clove", aisle: "produce" },
      { name: "Lemon", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Parsley", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Red pepper flakes", qty: 1, unit: "tsp", aisle: "spice" },
    ],
    steps: [
      "Boil linguine in well-salted water until al dente. Reserve ½ cup pasta water before draining.",
      "Pat shrimp dry, season with salt. Thinly slice garlic; chop parsley.",
      "Melt half the butter over medium heat. Add garlic and red pepper flakes, cook 30 sec until fragrant.",
      "Add shrimp in a single layer, 90 sec per side until pink. Squeeze in lemon juice, add remaining butter.",
      "Toss drained pasta into the pan with pasta water until silky. Finish with parsley and lemon zest.",
    ],
    source: src("Shrimp scampi", "bonappetit.com"),
  },
  {
    id: "bbq-chicken-flatbread",
    name: "BBQ Chicken Flatbread",
    categories: ["standard"],
    emoji: "🍕",
    color: "from-red-200 to-amber-200",
    blurb: "Smoky BBQ chicken, red onion, mozzarella on crisp flatbread.",
    time: 25, calories: 680, protein: 38,
    ingredients: [
      { name: "Chicken breast", qty: 350, unit: "g", aisle: "protein" },
      { name: "Flatbread", qty: 2, unit: "piece", aisle: "grains" },
      { name: "BBQ sauce", qty: 0.5, unit: "cup", aisle: "condiment" },
      { name: "Mozzarella cheese", qty: 150, unit: "g", aisle: "dairy" },
      { name: "Red onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Preheat oven to 230°C / 450°F with a baking sheet inside.",
      "Season and sear chicken until cooked through, 5 min per side. Rest, then dice and toss with 3 tbsp BBQ sauce.",
      "Spread remaining BBQ sauce on flatbreads. Top with mozzarella, chicken, and thinly sliced red onion.",
      "Bake on the hot sheet 8–10 min until cheese is melted and edges are crisp.",
      "Finish with fresh cilantro and a drizzle more BBQ sauce.",
    ],
    source: src("BBQ chicken flatbread pizza", "seriouseats.com"),
  },

  // ───────────── HIGH-PROTEIN ─────────────
  {
    id: "steak-chimichurri",
    name: "Seared Steak with Chimichurri",
    categories: ["high-protein"],
    emoji: "🥩",
    color: "from-rose-300 to-red-200",
    blurb: "Garlic-crusted steak, bright herby chimichurri, roasted potatoes.",
    time: 30, calories: 710, protein: 58,
    ingredients: [
      { name: "Sirloin steak", qty: 500, unit: "g", aisle: "protein" },
      { name: "Baby potatoes", qty: 500, unit: "g", aisle: "produce" },
      { name: "Parsley", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Red wine vinegar", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Olive oil", qty: 4, unit: "tbsp", aisle: "condiment" },
      { name: "Red pepper flakes", qty: 1, unit: "tsp", aisle: "spice" },
    ],
    steps: [
      "Preheat oven to 220°C / 425°F. Halve baby potatoes, toss with oil, salt; roast 25 min, cut side down, until crisp.",
      "Finely chop parsley, cilantro, and 3 garlic cloves. Mix with red wine vinegar, olive oil, red pepper flakes, and salt → chimichurri; let sit 10 min.",
      "Pat steak dry, salt heavily. Sear in a smoking-hot cast iron 3 min per side for medium-rare.",
      "Rest steak 5 min under foil. Slice against the grain.",
      "Plate potatoes, steak, and spoon chimichurri generously over the top.",
    ],
    source: src("Seared steak with chimichurri", "seriouseats.com"),
  },
  {
    id: "greek-chicken-bowl",
    name: "Greek Chicken Power Bowl",
    categories: ["high-protein"],
    emoji: "🥗",
    color: "from-sky-200 to-cyan-200",
    blurb: "Lemon-oregano chicken, quinoa, tzatziki, olives, crisp cucumber.",
    time: 30, calories: 580, protein: 52,
    ingredients: [
      { name: "Chicken breast", qty: 500, unit: "g", aisle: "protein" },
      { name: "Quinoa", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Greek yogurt", qty: 1, unit: "cup", aisle: "dairy" },
      { name: "Cucumber", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Kalamata olives", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "Cherry tomatoes", qty: 250, unit: "g", aisle: "produce" },
      { name: "Feta cheese", qty: 80, unit: "g", aisle: "dairy" },
      { name: "Lemon", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Oregano", qty: 1, unit: "tsp", aisle: "spice" },
    ],
    steps: [
      "Marinate chicken in lemon juice, olive oil, oregano, salt, and pepper for 10 min.",
      "Rinse quinoa and cook in 2 cups water with salt, 15 min, then fluff.",
      "Make tzatziki: grated cucumber (squeezed), yogurt, minced garlic, lemon, salt, dill.",
      "Sear chicken 5–6 min per side until golden and 74°C/165°F internal. Rest and slice.",
      "Build bowls: quinoa, chicken, halved tomatoes, cucumber, olives, feta, tzatziki, extra lemon.",
    ],
    source: src("Greek chicken quinoa bowl", "cooking.nytimes.com"),
  },
  {
    id: "tuna-poke",
    name: "Spicy Tuna Poke Bowl",
    categories: ["high-protein"],
    emoji: "🍣",
    color: "from-pink-200 to-rose-200",
    blurb: "Sushi-grade tuna, avocado, edamame, sesame-soy drizzle.",
    time: 15, calories: 540, protein: 42,
    ingredients: [
      { name: "Sushi-grade tuna", qty: 400, unit: "g", aisle: "protein" },
      { name: "Sushi rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Avocado", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Edamame", qty: 1, unit: "cup", aisle: "frozen" },
      { name: "Soy sauce", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Sriracha", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Sesame oil", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Green onion", qty: 3, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Rinse sushi rice until water runs clear, cook per package. Season with 1 tbsp rice vinegar + pinch sugar + salt.",
      "Blanch edamame in salted boiling water 3 min, shock in ice water.",
      "Dice tuna into ½-inch cubes. Toss gently with soy sauce, sriracha, and sesame oil.",
      "Slice avocado and green onions.",
      "Assemble bowls: warm rice, tuna, avocado, edamame, scallions. Drizzle with extra sauce.",
    ],
    source: src("Spicy tuna poke bowl", "bonappetit.com"),
  },
  {
    id: "cottage-power-eggs",
    name: "Cottage Cheese Power Scramble",
    categories: ["high-protein"],
    emoji: "🍳",
    color: "from-yellow-100 to-orange-100",
    blurb: "Creamy scramble with cottage cheese, spinach, sourdough toast.",
    time: 15, calories: 480, protein: 40,
    ingredients: [
      { name: "Egg", qty: 8, unit: "piece", aisle: "dairy" },
      { name: "Cottage cheese", qty: 1, unit: "cup", aisle: "dairy" },
      { name: "Spinach", qty: 200, unit: "g", aisle: "produce" },
      { name: "Sourdough bread", qty: 4, unit: "slice", aisle: "grains" },
      { name: "Butter", qty: 2, unit: "tbsp", aisle: "dairy" },
      { name: "Chives", qty: 1, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Whisk eggs with a big pinch of salt and ½ cup of the cottage cheese until loose.",
      "Toast sourdough and butter it generously.",
      "Melt butter in a non-stick skillet over medium-low. Add spinach and wilt 1 min.",
      "Pour in eggs. Stir slowly and constantly until just set but still glossy, 3–4 min.",
      "Top toast with eggs, remaining cottage cheese dollops, and snipped chives.",
    ],
    source: src("Cottage cheese scrambled eggs", "seriouseats.com"),
  },

  // ───────────── VEGAN ─────────────
  {
    id: "chickpea-curry",
    name: "Coconut Chickpea Curry",
    categories: ["vegan", "high-protein"],
    emoji: "🍛",
    color: "from-yellow-200 to-orange-200",
    blurb: "Golden chickpea curry in coconut-tomato sauce with basmati rice.",
    time: 30, calories: 560, protein: 22,
    ingredients: [
      { name: "Chickpeas", qty: 2, unit: "can", aisle: "pantry" },
      { name: "Coconut milk", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Diced tomatoes", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Basmati rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { name: "Curry powder", qty: 2, unit: "tbsp", aisle: "spice" },
      { name: "Spinach", qty: 150, unit: "g", aisle: "produce" },
    ],
    steps: [
      "Start basmati rice. Dice onion, mince garlic and ginger.",
      "Sauté onion in oil until golden, 6 min. Add garlic, ginger, curry powder; toast 1 min.",
      "Stir in diced tomatoes and simmer 3 min to concentrate.",
      "Add coconut milk and drained chickpeas. Simmer 10 min until thickened and glossy.",
      "Fold in spinach until wilted. Season with salt and lemon juice. Serve over rice.",
    ],
    source: src("Coconut chickpea curry", "minimalistbaker.com"),
  },
  {
    id: "tofu-banh-mi",
    name: "Crispy Tofu Bánh Mì",
    categories: ["vegan", "high-protein"],
    emoji: "🥖",
    color: "from-lime-200 to-yellow-200",
    blurb: "Golden-crusted tofu, quick-pickled veg, sriracha mayo, baguette.",
    time: 30, calories: 620, protein: 32,
    ingredients: [
      { name: "Extra firm tofu", qty: 400, unit: "g", aisle: "plantProtein" },
      { name: "Baguette", qty: 2, unit: "piece", aisle: "grains" },
      { name: "Carrot", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Daikon radish", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cucumber", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Vegan mayo", qty: 4, unit: "tbsp", aisle: "condiment" },
      { name: "Sriracha", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Rice vinegar", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Soy sauce", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Press tofu 15 min. Julienne carrot and daikon, toss with rice vinegar, 1 tsp sugar, salt. Let pickle.",
      "Slice tofu into ½-inch slabs, coat lightly in cornstarch and soy sauce.",
      "Pan-fry tofu in neutral oil until deeply golden on all sides, about 8 min total.",
      "Mix mayo with sriracha. Slice cucumber into planks.",
      "Split and lightly toast baguettes. Smear with sriracha mayo, layer tofu, pickled veg, cucumber, and big handfuls of cilantro.",
    ],
    source: src("Crispy tofu banh mi", "bonappetit.com"),
  },
  {
    id: "lentil-bolognese",
    name: "Red Lentil Bolognese",
    categories: ["vegan", "high-protein"],
    emoji: "🍝",
    color: "from-red-200 to-rose-200",
    blurb: "Rich, slow-simmered red lentil ragu over pappardelle.",
    time: 40, calories: 590, protein: 28,
    ingredients: [
      { name: "Red lentils", qty: 1, unit: "cup", aisle: "pantry" },
      { name: "Pappardelle", qty: 225, unit: "g", aisle: "grains" },
      { name: "Crushed tomatoes", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Carrot", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Celery", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Tomato paste", qty: 2, unit: "tbsp", aisle: "pantry" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Finely dice onion, carrot, and celery (soffritto). Mince garlic.",
      "Sauté soffritto in olive oil until soft and sweet, 10 min. Add garlic and tomato paste; cook 2 min until brick red.",
      "Stir in crushed tomatoes, rinsed lentils, 2 cups water, salt. Simmer uncovered 25 min, stirring, until lentils collapse into a ragu.",
      "Cook pappardelle in heavily salted water until al dente.",
      "Toss pasta with ragu, adding a splash of pasta water to loosen. Finish with olive oil and black pepper.",
    ],
    source: src("Red lentil bolognese", "minimalistbaker.com"),
  },
  {
    id: "buddha-bowl",
    name: "Miso Tahini Buddha Bowl",
    categories: ["vegan"],
    emoji: "🥙",
    color: "from-emerald-200 to-teal-200",
    blurb: "Roasted sweet potato, kale, chickpeas, miso-tahini drizzle.",
    time: 35, calories: 520, protein: 18,
    ingredients: [
      { name: "Sweet potato", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Kale", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Chickpeas", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Quinoa", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Tahini", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "White miso", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Lemon", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Avocado", qty: 1, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Preheat oven to 220°C / 425°F. Cube sweet potato; drain and dry chickpeas. Toss both with oil, salt; roast 25 min.",
      "Cook quinoa in 2 cups salted water, 15 min.",
      "Massage torn kale with a pinch of salt and olive oil until softened.",
      "Whisk tahini, miso, lemon juice, and 3–4 tbsp warm water into a pourable dressing.",
      "Build bowls: quinoa base, kale, sweet potato, chickpeas, sliced avocado, generous miso-tahini drizzle.",
    ],
    source: src("Miso tahini buddha bowl", "minimalistbaker.com"),
  },
  {
    id: "black-bean-enchiladas",
    name: "Black Bean Enchiladas",
    categories: ["vegan", "high-protein"],
    emoji: "🌯",
    color: "from-orange-200 to-rose-300",
    blurb: "Black beans, charred corn, red enchilada sauce, cashew crema.",
    time: 40, calories: 610, protein: 26,
    ingredients: [
      { name: "Black beans", qty: 2, unit: "can", aisle: "pantry" },
      { name: "Flour tortillas", qty: 8, unit: "piece", aisle: "grains" },
      { name: "Enchilada sauce", qty: 2, unit: "cup", aisle: "pantry" },
      { name: "Frozen corn", qty: 1, unit: "cup", aisle: "frozen" },
      { name: "Red onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cashews", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "Lime", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cumin", qty: 1, unit: "tsp", aisle: "spice" },
    ],
    steps: [
      "Soak cashews in hot water 15 min. Blend with ½ cup water, lime juice, and salt until silky → crema.",
      "Preheat oven to 200°C / 400°F. Char corn in a dry skillet 3 min. Sauté diced onion, add drained beans, cumin, ½ cup enchilada sauce; mash lightly.",
      "Warm tortillas to make pliable. Fill each with bean mix, roll, and line up seam-down in a baking dish.",
      "Pour remaining sauce over, cover with foil; bake 20 min.",
      "Uncover, drizzle with cashew crema, scatter cilantro and lime. Done.",
    ],
    source: src("Vegan black bean enchiladas", "minimalistbaker.com"),
  },
  {
    id: "tempeh-stirfry",
    name: "Tempeh Peanut Stir-Fry",
    categories: ["vegan", "high-protein"],
    emoji: "🥜",
    color: "from-amber-200 to-yellow-300",
    blurb: "Crispy tempeh, broccoli, peppers, creamy peanut-ginger sauce.",
    time: 25, calories: 610, protein: 34,
    ingredients: [
      { name: "Tempeh", qty: 400, unit: "g", aisle: "plantProtein" },
      { name: "Broccoli", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Bell pepper", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Peanut butter", qty: 3, unit: "tbsp", aisle: "pantry" },
      { name: "Soy sauce", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { name: "Lime", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Jasmine rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Garlic", qty: 3, unit: "clove", aisle: "produce" },
    ],
    steps: [
      "Start rice. Steam tempeh cubes 8 min to mellow bitterness; pat dry.",
      "Whisk peanut butter, soy sauce, lime juice, grated ginger, minced garlic, and 3–4 tbsp warm water into a sauce.",
      "Sear tempeh in a hot oiled skillet until crisp on all sides, 6 min.",
      "Add chopped broccoli and peppers; stir-fry 4 min. Add a splash of water, cover, steam 2 min.",
      "Pour sauce in, toss until glossy. Serve over rice with extra lime.",
    ],
    source: src("Peanut tempeh stir fry", "minimalistbaker.com"),
  },
  {
    id: "mushroom-risotto",
    name: "Wild Mushroom Risotto",
    categories: ["vegan"],
    emoji: "🍄",
    color: "from-stone-200 to-amber-200",
    blurb: "Creamy arborio rice, mixed mushrooms, thyme, nutritional yeast.",
    time: 40, calories: 540, protein: 14,
    ingredients: [
      { name: "Arborio rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Mixed mushrooms", qty: 400, unit: "g", aisle: "produce" },
      { name: "Vegetable broth", qty: 4, unit: "cup", aisle: "pantry" },
      { name: "Shallot", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 3, unit: "clove", aisle: "produce" },
      { name: "White wine", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "Nutritional yeast", qty: 3, unit: "tbsp", aisle: "pantry" },
      { name: "Thyme", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Warm broth in a saucepan, keep simmering nearby.",
      "Sear sliced mushrooms in oil in a wide pan over high heat until deeply browned. Season, remove half for topping.",
      "Lower heat, add minced shallot and garlic; cook 2 min. Stir in rice and thyme, toast 1 min.",
      "Deglaze with wine and stir until absorbed. Add broth a ladle at a time, stirring, until rice is creamy and al dente, about 20 min.",
      "Off heat, stir in nutritional yeast and a glug of olive oil. Top with reserved mushrooms.",
    ],
    source: src("Vegan mushroom risotto", "bonappetit.com"),
  },
  {
    id: "seitan-shawarma",
    name: "Seitan Shawarma Wraps",
    categories: ["vegan", "high-protein"],
    emoji: "🌯",
    color: "from-orange-300 to-amber-300",
    blurb: "Spiced seitan, garlic tahini, pickled onions, warm pita.",
    time: 30, calories: 600, protein: 38,
    ingredients: [
      { name: "Seitan", qty: 400, unit: "g", aisle: "plantProtein" },
      { name: "Pita bread", qty: 4, unit: "piece", aisle: "grains" },
      { name: "Tahini", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Red onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Lemon", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Cucumber", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Tomato", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Cumin", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Smoked paprika", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Garlic", qty: 3, unit: "clove", aisle: "produce" },
    ],
    steps: [
      "Slice red onion thin, toss with juice of 1 lemon and a big pinch of salt; let pickle.",
      "Slice seitan thin, toss with olive oil, cumin, smoked paprika, salt.",
      "Whisk tahini with juice of remaining lemon, minced garlic, salt, and warm water until creamy.",
      "Sear seitan on high heat until crisp-edged and caramelized, about 5 min.",
      "Warm pitas. Fill with seitan, tomato, cucumber, pickled onions, and a heavy drizzle of tahini.",
    ],
    source: src("Seitan shawarma wraps", "bonappetit.com"),
  },
  {
    id: "cauliflower-tacos",
    name: "Crispy Cauliflower Tacos",
    categories: ["vegan"],
    emoji: "🌮",
    color: "from-lime-200 to-green-200",
    blurb: "Chili-lime roasted cauliflower, slaw, avocado, corn tortillas.",
    time: 30, calories: 480, protein: 14,
    ingredients: [
      { name: "Cauliflower", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Corn tortillas", qty: 8, unit: "piece", aisle: "grains" },
      { name: "Avocado", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Red cabbage", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Lime", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Chili powder", qty: 1, unit: "tbsp", aisle: "spice" },
      { name: "Cumin", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Preheat oven to 230°C / 450°F. Cut cauliflower into bite-sized florets.",
      "Toss florets with olive oil, chili powder, cumin, salt. Roast 22 min until charred at the edges.",
      "Shred red cabbage; toss with juice of 1 lime and salt for a quick slaw.",
      "Mash avocado with lime, salt, and chopped cilantro.",
      "Char tortillas. Build: avocado smear, cauliflower, slaw, more cilantro, lime wedge.",
    ],
    source: src("Crispy cauliflower tacos", "minimalistbaker.com"),
  },
  {
    id: "edamame-soba",
    name: "Edamame Soba Noodle Bowl",
    categories: ["vegan", "high-protein"],
    emoji: "🍜",
    color: "from-emerald-200 to-lime-200",
    blurb: "Chilled soba, edamame, cucumber, sesame-ginger dressing.",
    time: 20, calories: 500, protein: 28,
    ingredients: [
      { name: "Soba noodles", qty: 225, unit: "g", aisle: "grains" },
      { name: "Edamame", qty: 2, unit: "cup", aisle: "frozen" },
      { name: "Cucumber", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Carrot", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Green onion", qty: 3, unit: "piece", aisle: "produce" },
      { name: "Soy sauce", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Sesame oil", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Rice vinegar", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { name: "Sesame seeds", qty: 1, unit: "tbsp", aisle: "pantry" },
    ],
    steps: [
      "Boil soba per package directions, drain, rinse under cold water until chilled.",
      "Blanch edamame 3 min in the same pot; shock in ice water.",
      "Whisk soy sauce, sesame oil, rice vinegar, grated ginger, and a pinch of sugar.",
      "Julienne cucumber and carrot; slice green onion.",
      "Toss soba with dressing, pile bowls with edamame, cucumber, carrot, scallions. Shower with sesame seeds.",
    ],
    source: src("Cold soba noodle bowl with edamame", "cooking.nytimes.com"),
  },

  // ───────────── MORE CLASSIC ─────────────
  {
    id: "sheet-pan-sausage",
    name: "Sheet-Pan Italian Sausage & Peppers",
    categories: ["standard", "high-protein"],
    emoji: "🌶️",
    color: "from-red-200 to-orange-200",
    blurb: "Sweet Italian sausage, bell peppers, and onions roasted on one pan.",
    time: 30, calories: 620, protein: 34,
    ingredients: [
      { name: "Italian sausage", qty: 500, unit: "g", aisle: "protein" },
      { name: "Bell pepper", qty: 3, unit: "piece", aisle: "produce" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Oregano", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Crusty bread", qty: 4, unit: "slice", aisle: "grains" },
    ],
    steps: [
      "Heat oven to 220°C / 425°F. Slice peppers and onion into wide strips; smash garlic.",
      "Toss vegetables with olive oil, oregano, salt, and pepper on a sheet pan.",
      "Nestle sausages among the vegetables. Roast 25 min, tossing once, until sausages are browned and peppers slightly charred.",
      "Serve piled onto toasted bread or over polenta.",
    ],
    source: src("Sheet pan sausage and peppers", "cooking.nytimes.com"),
  },
  {
    id: "lemon-butter-cod",
    name: "Lemon-Butter Cod with Orzo",
    categories: ["standard", "high-protein"],
    emoji: "🐟",
    color: "from-sky-200 to-yellow-200",
    blurb: "Flaky cod in lemon-caper butter over herbed orzo.",
    time: 25, calories: 540, protein: 42,
    ingredients: [
      { name: "Cod fillet", qty: 500, unit: "g", aisle: "protein" },
      { name: "Orzo", qty: 200, unit: "g", aisle: "grains" },
      { name: "Butter", qty: 4, unit: "tbsp", aisle: "dairy" },
      { name: "Lemon", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Capers", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Parsley", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 2, unit: "clove", aisle: "produce" },
      { name: "Olive oil", qty: 1, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Cook orzo in salted boiling water until al dente; drain, reserve ½ cup pasta water.",
      "Pat cod dry, season with salt and pepper. Sear in olive oil 3 min per side until just flaky; remove.",
      "Melt butter with garlic and capers, deglaze with lemon juice and a splash of pasta water.",
      "Toss orzo with half the butter sauce and chopped parsley. Plate, top with cod, spoon remaining sauce over.",
    ],
    source: src("Lemon butter cod with orzo", "cooking.nytimes.com"),
  },
  {
    id: "bacon-cheeseburger",
    name: "Smash Bacon Cheeseburger",
    categories: ["standard", "high-protein"],
    emoji: "🍔",
    color: "from-amber-200 to-red-300",
    blurb: "Crispy-edged smash patties, bacon, American cheese, soft buns.",
    time: 20, calories: 780, protein: 46,
    ingredients: [
      { name: "Ground beef (80/20)", qty: 500, unit: "g", aisle: "protein" },
      { name: "Bacon", qty: 6, unit: "slice", aisle: "protein" },
      { name: "American cheese", qty: 4, unit: "slice", aisle: "dairy" },
      { name: "Brioche buns", qty: 4, unit: "piece", aisle: "grains" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Pickles", qty: 0.5, unit: "cup", aisle: "condiment" },
      { name: "Mayonnaise", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Ketchup", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Crisp bacon in a cast-iron skillet; reserve drippings and drain bacon.",
      "Form beef into loose 125g balls. In the hot skillet, press each ball flat with a spatula for 60 seconds.",
      "Flip patties, top with cheese and a spoon of diced onion, cover 30 seconds to melt.",
      "Toast buns in bacon fat. Build: bun, mayo-ketchup, patty, bacon, pickles, bun.",
    ],
    source: src("Smash burger recipe", "seriouseats.com"),
  },
  {
    id: "thai-basil-chicken",
    name: "Thai Basil Chicken (Pad Kra Pao)",
    categories: ["standard", "high-protein"],
    emoji: "🌿",
    color: "from-lime-200 to-emerald-200",
    blurb: "Minced chicken, chili, basil, crispy fried egg over jasmine rice.",
    time: 20, calories: 640, protein: 45,
    ingredients: [
      { name: "Ground chicken", qty: 500, unit: "g", aisle: "protein" },
      { name: "Jasmine rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Thai basil", qty: 2, unit: "cup", aisle: "produce" },
      { name: "Garlic", qty: 6, unit: "clove", aisle: "produce" },
      { name: "Thai chili", qty: 4, unit: "piece", aisle: "produce" },
      { name: "Oyster sauce", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Soy sauce", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Fish sauce", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Egg", qty: 4, unit: "piece", aisle: "dairy" },
      { name: "Vegetable oil", qty: 3, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Cook jasmine rice. Pound garlic and chilies into a rough paste.",
      "Heat oil over high; stir-fry garlic-chili paste 30 seconds until fragrant.",
      "Add ground chicken, break up and brown. Stir in oyster, soy, and fish sauces plus a splash of water.",
      "Kill heat, fold in Thai basil until just wilted.",
      "In fresh oil, fry eggs until edges are crispy and lacy. Serve chicken over rice topped with the egg.",
    ],
    source: src("Pad kra pao gai", "hot-thai-kitchen.com"),
  },
  {
    id: "pesto-gnocchi",
    name: "Crispy Pesto Gnocchi with Peas",
    categories: ["standard"],
    emoji: "🥫",
    color: "from-green-200 to-emerald-200",
    blurb: "Pan-fried gnocchi, bright basil pesto, sweet peas, parmesan.",
    time: 20, calories: 610, protein: 18,
    ingredients: [
      { name: "Potato gnocchi", qty: 500, unit: "g", aisle: "grains" },
      { name: "Basil pesto", qty: 0.5, unit: "cup", aisle: "condiment" },
      { name: "Frozen peas", qty: 1, unit: "cup", aisle: "frozen" },
      { name: "Parmesan", qty: 40, unit: "g", aisle: "dairy" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Lemon", qty: 1, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Heat olive oil in a large skillet. Add gnocchi straight from the package (no boiling).",
      "Cook undisturbed 3–4 min until golden, then toss and crisp the other side another 3 min.",
      "Add peas, toss 1 minute to heat through.",
      "Off heat, stir in pesto and a squeeze of lemon. Shower with parmesan.",
    ],
    source: src("Crispy pesto gnocchi", "bonappetit.com"),
  },
  {
    id: "carnitas-bowl",
    name: "Slow-Cooker Carnitas Bowl",
    categories: ["standard", "high-protein"],
    emoji: "🫔",
    color: "from-orange-200 to-amber-200",
    blurb: "Citrus-braised pork, cilantro-lime rice, black beans, pickled onion.",
    time: 30, calories: 690, protein: 44,
    ingredients: [
      { name: "Pork shoulder", qty: 900, unit: "g", aisle: "protein" },
      { name: "Orange", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Lime", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Red onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Black beans", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Long-grain rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cumin", qty: 1, unit: "tbsp", aisle: "spice" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
    ],
    steps: [
      "Cube pork and rub with cumin, salt, pepper, and smashed garlic. Slow-cook with orange juice and peel for 6–8 hours on low (or 4 on high).",
      "Shred pork, then crisp under broiler on a sheet pan 5 min.",
      "Cook rice; fluff with lime zest and chopped cilantro.",
      "Quick-pickle thinly sliced red onion in lime juice with a pinch of salt, 10 min.",
      "Bowl rice, black beans, carnitas, pickled onion, and a lime wedge.",
    ],
    source: src("Slow cooker carnitas", "cooking.nytimes.com"),
  },
  {
    id: "chicken-piccata",
    name: "Lemon Chicken Piccata",
    categories: ["standard", "high-protein"],
    emoji: "🍋",
    color: "from-yellow-200 to-amber-200",
    blurb: "Pan-seared chicken cutlets in a bright lemon-caper pan sauce.",
    time: 25, calories: 560, protein: 48,
    ingredients: [
      { name: "Chicken breast", qty: 500, unit: "g", aisle: "protein" },
      { name: "Flour", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "Butter", qty: 3, unit: "tbsp", aisle: "dairy" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Lemon", qty: 2, unit: "piece", aisle: "produce" },
      { name: "Capers", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Chicken stock", qty: 0.75, unit: "cup", aisle: "pantry" },
      { name: "Parsley", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Angel hair pasta", qty: 225, unit: "g", aisle: "grains" },
    ],
    steps: [
      "Butterfly and pound chicken breasts to ½-inch; season and dredge in flour.",
      "Sear in oil and 1 tbsp butter, 3 min per side; transfer to plate.",
      "Deglaze with lemon juice, stock, and capers; reduce 2 min. Finish sauce with remaining butter.",
      "Return chicken to pan to coat. Cook angel hair, toss with a spoonful of sauce and parsley, and serve chicken on top.",
    ],
    source: src("Chicken piccata", "cooking.nytimes.com"),
  },

  // ───────────── MORE VEGAN ─────────────
  {
    id: "miso-glazed-tofu",
    name: "Miso-Glazed Tofu with Broccoli",
    categories: ["vegan", "high-protein"],
    emoji: "🥢",
    color: "from-amber-200 to-emerald-200",
    blurb: "Crispy tofu in sweet-savory miso glaze with charred broccoli and rice.",
    time: 30, calories: 540, protein: 32,
    ingredients: [
      { name: "Extra-firm tofu", qty: 500, unit: "g", aisle: "plantProtein" },
      { name: "White miso", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Maple syrup", qty: 2, unit: "tbsp", aisle: "pantry" },
      { name: "Soy sauce", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Rice vinegar", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Broccoli", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Jasmine rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Sesame oil", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Sesame seeds", qty: 1, unit: "tbsp", aisle: "pantry" },
    ],
    steps: [
      "Press tofu 15 min, cube, and toss with a little cornstarch. Cook rice.",
      "Whisk miso, maple, soy, rice vinegar, and 2 tbsp water into a glaze.",
      "Pan-fry tofu in sesame oil until golden all over, 8 min. Pour glaze over and toss to coat.",
      "Separately sear broccoli florets until charred and crisp-tender, 5 min.",
      "Plate rice, tofu, and broccoli; finish with sesame seeds.",
    ],
    source: src("Miso glazed tofu", "cooking.nytimes.com"),
  },
  {
    id: "dal-makhani",
    name: "Creamy Dal Makhani",
    categories: ["vegan"],
    emoji: "🍲",
    color: "from-amber-200 to-rose-200",
    blurb: "Slow-simmered black lentils, tomato, and coconut cream with basmati.",
    time: 40, calories: 520, protein: 22,
    ingredients: [
      { name: "Black lentils (urad dal)", qty: 1, unit: "cup", aisle: "pantry" },
      { name: "Tomato", qty: 3, unit: "piece", aisle: "produce" },
      { name: "Coconut cream", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 5, unit: "clove", aisle: "produce" },
      { name: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { name: "Garam masala", qty: 2, unit: "tsp", aisle: "spice" },
      { name: "Cumin", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Basmati rice", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Vegetable oil", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Soak lentils 1 hour (or use canned). Simmer with plenty of water until very tender, 30 min.",
      "Meanwhile sauté onion in oil until golden, add grated garlic and ginger, then spices.",
      "Add diced tomato; cook down 10 min into a jammy base.",
      "Stir cooked lentils (plus their cooking liquid) into the base. Simmer 10 min, mashing some for creaminess.",
      "Swirl in coconut cream. Serve over basmati.",
    ],
    source: src("Dal makhani", "cooking.nytimes.com"),
  },
  {
    id: "vegan-pho",
    name: "Vegan Pho with Mushrooms",
    categories: ["vegan"],
    emoji: "🍜",
    color: "from-amber-200 to-red-200",
    blurb: "Star-anise-scented broth, rice noodles, shiitake, and fresh herbs.",
    time: 35, calories: 480, protein: 16,
    ingredients: [
      { name: "Rice noodles", qty: 225, unit: "g", aisle: "grains" },
      { name: "Shiitake mushrooms", qty: 200, unit: "g", aisle: "produce" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Ginger", qty: 50, unit: "g", aisle: "produce" },
      { name: "Star anise", qty: 3, unit: "piece", aisle: "spice" },
      { name: "Cinnamon stick", qty: 1, unit: "piece", aisle: "spice" },
      { name: "Vegetable stock", qty: 6, unit: "cup", aisle: "pantry" },
      { name: "Soy sauce", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Bean sprouts", qty: 2, unit: "cup", aisle: "produce" },
      { name: "Thai basil", qty: 1, unit: "cup", aisle: "produce" },
      { name: "Lime", qty: 2, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Char halved onion and unpeeled ginger under the broiler until blackened, 6 min.",
      "Toast star anise and cinnamon 30 sec in a pot; add charred aromatics, stock, soy. Simmer 20 min, strain.",
      "Sear shiitake until deeply browned.",
      "Soak rice noodles in hot water until pliable.",
      "Bowl noodles and mushrooms, ladle hot broth over, pile with sprouts, basil, and lime.",
    ],
    source: src("Vegan pho", "cooking.nytimes.com"),
  },
  {
    id: "harissa-chickpea-stew",
    name: "Harissa Chickpea & Kale Stew",
    categories: ["vegan", "high-protein"],
    emoji: "🥘",
    color: "from-rose-200 to-orange-200",
    blurb: "Smoky harissa, chickpeas, kale, lemon — finished with crusty bread.",
    time: 25, calories: 460, protein: 22,
    ingredients: [
      { name: "Chickpeas", qty: 2, unit: "can", aisle: "pantry" },
      { name: "Harissa paste", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Crushed tomatoes", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Kale", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Lemon", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Olive oil", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Crusty bread", qty: 4, unit: "slice", aisle: "grains" },
    ],
    steps: [
      "Sauté diced onion in olive oil until soft; add garlic and harissa, bloom 1 min.",
      "Stir in tomatoes and drained chickpeas; simmer 10 min until thickened.",
      "Add torn kale and a splash of water, cook 3 min until wilted.",
      "Finish with lemon juice and a drizzle of olive oil. Serve with charred bread for dipping.",
    ],
    source: src("Harissa chickpea stew", "cooking.nytimes.com"),
  },
  {
    id: "peanut-noodles",
    name: "Cold Peanut Sesame Noodles",
    categories: ["vegan"],
    emoji: "🥜",
    color: "from-amber-200 to-yellow-200",
    blurb: "Slurpable wheat noodles tossed in creamy chili-peanut sauce.",
    time: 15, calories: 560, protein: 18,
    ingredients: [
      { name: "Udon or lo mein noodles", qty: 300, unit: "g", aisle: "grains" },
      { name: "Peanut butter", qty: 0.33, unit: "cup", aisle: "pantry" },
      { name: "Soy sauce", qty: 3, unit: "tbsp", aisle: "condiment" },
      { name: "Rice vinegar", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Chili crisp", qty: 1, unit: "tbsp", aisle: "condiment" },
      { name: "Maple syrup", qty: 1, unit: "tbsp", aisle: "pantry" },
      { name: "Garlic", qty: 2, unit: "clove", aisle: "produce" },
      { name: "Cucumber", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Green onion", qty: 3, unit: "piece", aisle: "produce" },
      { name: "Peanuts", qty: 3, unit: "tbsp", aisle: "pantry" },
    ],
    steps: [
      "Boil noodles, drain, rinse cold; toss with a splash of sesame oil.",
      "Whisk peanut butter, soy, rice vinegar, chili crisp, maple, grated garlic, and 3 tbsp hot water until silky.",
      "Toss noodles with sauce; pile on julienned cucumber and sliced scallions.",
      "Top with crushed peanuts and extra chili crisp.",
    ],
    source: src("Cold peanut noodles", "cooking.nytimes.com"),
  },
  {
    id: "stuffed-peppers",
    name: "Quinoa-Stuffed Peppers",
    categories: ["vegan", "high-protein"],
    emoji: "🫑",
    color: "from-red-200 to-lime-200",
    blurb: "Bell peppers stuffed with spiced quinoa, black beans, and corn.",
    time: 45, calories: 490, protein: 20,
    ingredients: [
      { name: "Bell pepper", qty: 4, unit: "piece", aisle: "produce" },
      { name: "Quinoa", qty: 1, unit: "cup", aisle: "grains" },
      { name: "Black beans", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Corn kernels", qty: 1, unit: "cup", aisle: "frozen" },
      { name: "Salsa", qty: 1, unit: "cup", aisle: "condiment" },
      { name: "Cumin", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Smoked paprika", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Lime", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Nutritional yeast", qty: 3, unit: "tbsp", aisle: "pantry" },
    ],
    steps: [
      "Heat oven to 200°C / 400°F. Halve and seed peppers; par-bake cut-side up 10 min.",
      "Cook quinoa in salted water. Fold in beans, corn, salsa, spices, and nutritional yeast.",
      "Mound filling into peppers. Cover with foil and bake 20 min, then uncover 5 min.",
      "Scatter cilantro and a squeeze of lime over the top to serve.",
    ],
    source: src("Quinoa stuffed peppers", "cooking.nytimes.com"),
  },
  {
    id: "vegan-chili",
    name: "Smoky Three-Bean Chili",
    categories: ["vegan", "high-protein"],
    emoji: "🌶",
    color: "from-red-300 to-amber-200",
    blurb: "Pinto, kidney, and black beans simmered with smoked paprika and chipotle.",
    time: 35, calories: 450, protein: 24,
    ingredients: [
      { name: "Pinto beans", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Kidney beans", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Black beans", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Crushed tomatoes", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Bell pepper", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Chipotle in adobo", qty: 2, unit: "tbsp", aisle: "condiment" },
      { name: "Smoked paprika", qty: 1, unit: "tbsp", aisle: "spice" },
      { name: "Cumin", qty: 1, unit: "tbsp", aisle: "spice" },
      { name: "Cocoa powder", qty: 1, unit: "tsp", aisle: "pantry" },
      { name: "Olive oil", qty: 2, unit: "tbsp", aisle: "condiment" },
    ],
    steps: [
      "Sweat diced onion, pepper, and garlic in oil, 6 min.",
      "Add chipotle, smoked paprika, cumin, and cocoa; toast 1 minute.",
      "Pour in tomatoes and drained beans plus 1 cup water. Simmer 20 min, partially covered.",
      "Season, smash a few beans against the pot to thicken, and serve with rice or cornbread.",
    ],
    source: src("Three bean vegan chili", "cooking.nytimes.com"),
  },
  {
    id: "coconut-lentil-soup",
    name: "Coconut Red Lentil Soup",
    categories: ["vegan", "high-protein"],
    emoji: "🥣",
    color: "from-amber-200 to-orange-300",
    blurb: "Red lentils in coconut-tomato broth with ginger and lime.",
    time: 30, calories: 440, protein: 20,
    ingredients: [
      { name: "Red lentils", qty: 1.5, unit: "cup", aisle: "pantry" },
      { name: "Coconut milk", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Crushed tomatoes", qty: 1, unit: "can", aisle: "pantry" },
      { name: "Vegetable stock", qty: 3, unit: "cup", aisle: "pantry" },
      { name: "Yellow onion", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { name: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { name: "Turmeric", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Cumin", qty: 1, unit: "tsp", aisle: "spice" },
      { name: "Lime", qty: 1, unit: "piece", aisle: "produce" },
      { name: "Cilantro", qty: 1, unit: "piece", aisle: "produce" },
    ],
    steps: [
      "Sauté onion, garlic, and ginger until soft, 5 min. Add turmeric and cumin.",
      "Stir in rinsed lentils, tomatoes, stock, and coconut milk. Simmer 20 min until lentils break down.",
      "Blend partially for a silky texture. Finish with lime juice.",
      "Top bowls with cilantro and a drizzle of chili oil if you like.",
    ],
    source: src("Coconut red lentil soup", "cooking.nytimes.com"),
  },
];

const CATEGORY_META = {
  "vegan": { label: "Vegan", accent: "bg-emerald-100 text-emerald-800 ring-emerald-200", dot: "bg-emerald-500" },
  "high-protein": { label: "High Protein", accent: "bg-rose-100 text-rose-800 ring-rose-200", dot: "bg-rose-500" },
  "standard": { label: "Classic", accent: "bg-amber-100 text-amber-800 ring-amber-200", dot: "bg-amber-500" },
};

window.__DATA__ = { MEALS, AISLES, CATEGORY_META };
})();
